<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	  <PackageReference Include="Scalar.AspNetCore" Version="2.16.12" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YpsAdmin.Database\YpsAdmin.Database.csproj" />
    <ProjectReference Include="..\YpsAdmin.Domain\YpsAdmin.Domain.csproj" />
    <ProjectReference Include="..\YpsAdmin.Shared\YpsAdmin.Shared.csproj" />
  </ItemGroup>

</Project>
